//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGPS {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGPS.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   앱 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_About {
            get {
                return ResourceManager.GetString("Main_MenuPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_Home {
            get {
                return ResourceManager.GetString("Main_MenuPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_RecordList {
            get {
                return ResourceManager.GetString("Main_MenuPage_RecordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음 세션 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_RecordSection {
            get {
                return ResourceManager.GetString("Main_MenuPage_RecordSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_Setting {
            get {
                return ResourceManager.GetString("Main_MenuPage_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다시 녹음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Re_Record {
            get {
                return ResourceManager.GetString("Re_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인에 성공했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SNSLogin_LoginSuccess {
            get {
                return ResourceManager.GetString("SNSLogin_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   네트워크 문제로 로그인할 수 없습니다 :(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SNSLogin_NetworkError {
            get {
                return ResourceManager.GetString("SNSLogin_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문제가 발생하여 로그인할 수 없습니다 :(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SNSLogin_UnknownError {
            get {
                return ResourceManager.GetString("SNSLogin_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나이를 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_AgePage_Title {
            get {
                return ResourceManager.GetString("UserFirstSet_AgePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_GenderPage_Female {
            get {
                return ResourceManager.GetString("UserFirstSet_GenderPage_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   남자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_GenderPage_Male {
            get {
                return ResourceManager.GetString("UserFirstSet_GenderPage_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성별을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_GenderPage_Title {
            get {
                return ResourceManager.GetString("UserFirstSet_GenderPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 항목을 채워주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_InputError_Blank {
            get {
                return ResourceManager.GetString("UserFirstSet_InputError_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10자 이하의 한글로 입력해 주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_InputError_OnlyKorean {
            get {
                return ResourceManager.GetString("UserFirstSet_InputError_OnlyKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름을 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_NamePage_Title {
            get {
                return ResourceManager.GetString("UserFirstSet_NamePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_NextButton_Finish {
            get {
                return ResourceManager.GetString("UserFirstSet_NextButton_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 단계로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_NextButton_Next {
            get {
                return ResourceManager.GetString("UserFirstSet_NextButton_Next", resourceCulture);
            }
        }
    }
}
