//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGPS {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGPS.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   앱 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_About {
            get {
                return ResourceManager.GetString("Main_MenuPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_Home {
            get {
                return ResourceManager.GetString("Main_MenuPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음 챕터 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_RecordChapter {
            get {
                return ResourceManager.GetString("Main_MenuPage_RecordChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_RecordList {
            get {
                return ResourceManager.GetString("Main_MenuPage_RecordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음 세션 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_RecordSection {
            get {
                return ResourceManager.GetString("Main_MenuPage_RecordSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_MenuPage_Setting {
            get {
                return ResourceManager.GetString("Main_MenuPage_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다시 녹음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Re_Record {
            get {
                return ResourceManager.GetString("Re_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음에 실패했습니다. 다시 녹음 해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RecordFail_Rerecord {
            get {
                return ResourceManager.GetString("RecordFail_Rerecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음 중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다시 업로드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReUpload {
            get {
                return ResourceManager.GetString("ReUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가만히
        ///가면
        ///가야지
        ///가자
        ///갈색
        ///갑자기
        ///갔었지
        ///갔지
        ///강하게
        ///걔야
        ///거기
        ///거기랑
        ///거기에
        ///거짓말
        ///건물?
        ///결석
        ///결혼?
        ///계단
        ///계속
        ///고마워
        ///고민됨
        ///공연?
        ///괜찮아
        ///구동
        ///귀엽네
        ///귀찮아
        ///그거
        ///그게
        ///그나마
        ///그날에
        ///그냥
        ///그니까
        ///그런데
        ///그럼
        ///그렇게
        ///그렇다
        ///그리고
        ///그만해
        ///그분을
        ///근데
        ///근육은
        ///글쎄다
        ///기본
        ///기뻤고
        ///기억력
        ///기억이
        ///김포?
        ///끝났지
        ///나는
        ///난민
        ///내가
        ///내과
        ///내일?
        ///냉면
        ///너가
        ///너는
        ///너무
        ///넘어가
        ///높지
        ///누가
        ///누나?
        ///다낭
        ///닭갈비
        ///담배?
        ///대박
        ///돈을
        ///됐어
        ///둘리
        ///뒤집어
        ///들켰고
        ///땅이
        ///때리냐
        ///라멘집
        ///마셨지
        ///많다고
        ///많이
        ///말해줘
        ///맛집?
        ///망해
        ///망했지
        ///맞아
        ///맞아요
        ///맞았지
        ///맞어
        ///맞잖아
        ///맞잖여
        ///맞지
        ///맨날
        ///멋있지
        ///몰라
        ///몰라요
        ///무섭다
        ///무엇?
        ///물어봐
        ///뭐라
        ///뭐를
        ///뭐야
        ///뭐지?
        ///뭔가
        ///뭔데
        ///바이킹
        ///배고파
        ///벌점?
        ///별로
        ///보내고
        ///볶음밥
        ///봐야지
        ///봤다고
        ///봤어
        ///봤지
        ///부럽다
        ///북한
        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Section1 {
            get {
                return ResourceManager.GetString("Section1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   짜증나
        ///짤렸대
        ///쨌든
        ///차마
        ///창업?
        ///창피해
        ///첫째
        ///체육
        ///최근에
        ///추워
        ///축구는
        ///충북
        ///친하면
        ///캐나다
        ///코트도
        ///탈모?
        ///터키?
        ///통계?
        ///특이해
        ///판촉?
        ///편해서
        ///포스터
        ///하겠지
        ///학교에
        ///한식?
        ///합격
        ///합정
        ///해야죠
        ///해야지
        ///핸드폰
        ///헤어져
        ///헬스
        ///호텔
        ///홍대
        ///홍콩
        ///화요일
        ///화장품
        ///화해해
        ///확실한
        ///효과
        ///훌쩍
        ///훔쳤어
        ///힘들어
        ///우유?
        ///우장산
        ///운동
        ///운전?
        ///울산
        ///울어?
        ///울음?
        ///웃겨요
        ///웃긴다
        ///웃지마
        ///워낙
        ///원두는
        ///원래?
        ///원래는
        ///원앙
        ///원장이
        ///원점
        ///원탑은
        ///월세
        ///웬일
        ///위에?
        ///위쪽?
        ///위치가
        ///위험해
        ///유격?
        ///유기농
        ///유도?
        ///유럽
        ///유로파
        ///유명한
        ///유아
        ///유치원
        ///유학은
        ///육군?
        ///육수가
        ///육십
        ///윤리
        ///융통성
        ///은행?
        ///은혜?
        ///음료수
        ///음식도
        ///음악
        ///음원?
        ///응원해
        ///의경
        ///의경은
        ///의대
        ///의무로
        ///의사가
        ///의외다
        ///의지가
        ///이거
        ///이끼
        ///이따가
        ///이란?
        ///이런
        ///이렇게
        ///이만해
        ///이미
        ///이백?
        ///이불?
        ///이뻐
        ///이상
        ///이상해
        ///이상형
        ///이[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Section2 {
            get {
                return ResourceManager.GetString("Section2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인에 성공했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SNSLogin_LoginSuccess {
            get {
                return ResourceManager.GetString("SNSLogin_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   네트워크 문제로 로그인할 수 없습니다 :(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SNSLogin_NetworkError {
            get {
                return ResourceManager.GetString("SNSLogin_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문제가 발생하여 로그인할 수 없습니다 :(과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SNSLogin_UnknownError {
            get {
                return ResourceManager.GetString("SNSLogin_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음 중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StopRecord {
            get {
                return ResourceManager.GetString("StopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드에 실패했습니다. 버튼을 눌러 다시 업로드를 시도 해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UploadFail_ReUpload {
            get {
                return ResourceManager.GetString("UploadFail_ReUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드 중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나이를 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_AgePage_Title {
            get {
                return ResourceManager.GetString("UserFirstSet_AgePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   병원 고유 번호를 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_CodePage_Title {
            get {
                return ResourceManager.GetString("UserFirstSet_CodePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_GenderPage_Female {
            get {
                return ResourceManager.GetString("UserFirstSet_GenderPage_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   남자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_GenderPage_Male {
            get {
                return ResourceManager.GetString("UserFirstSet_GenderPage_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성별을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_GenderPage_Title {
            get {
                return ResourceManager.GetString("UserFirstSet_GenderPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 이니셜을 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_InitialPage_Title {
            get {
                return ResourceManager.GetString("UserFirstSet_InitialPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 항목을 채워주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_InputError_Blank {
            get {
                return ResourceManager.GetString("UserFirstSet_InputError_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자 8자리를 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_InputError_Count8 {
            get {
                return ResourceManager.GetString("UserFirstSet_InputError_Count8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10자 이하의 한글로 입력해 주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_InputError_OnlyKorean {
            get {
                return ResourceManager.GetString("UserFirstSet_InputError_OnlyKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름을 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_NamePage_Title {
            get {
                return ResourceManager.GetString("UserFirstSet_NamePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_NextButton_Finish {
            get {
                return ResourceManager.GetString("UserFirstSet_NextButton_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 단계로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserFirstSet_NextButton_Next {
            get {
                return ResourceManager.GetString("UserFirstSet_NextButton_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개인별 초기 음성 보정 단계를 진행합니다. 
        ///본 단계는 음성 분석을 위한 중요한 단계이니 신중하게 녹음해주시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VoiceFirstSet_Info_Message {
            get {
                return ResourceManager.GetString("VoiceFirstSet_Info_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기 음성 보정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VoiceFirstSet_Info_Title {
            get {
                return ResourceManager.GetString("VoiceFirstSet_Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VoiceFirstSet_NextButton_Finish {
            get {
                return ResourceManager.GetString("VoiceFirstSet_NextButton_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 단계로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VoiceFirstSet_NextButton_Next {
            get {
                return ResourceManager.GetString("VoiceFirstSet_NextButton_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   녹음 버튼을 누르고 아래 단어를 10초간 발음하여
        ///3회 녹음하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VoiceFirstSet_Title {
            get {
                return ResourceManager.GetString("VoiceFirstSet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VoiceFirstSet_VoiceText_1 {
            get {
                return ResourceManager.GetString("VoiceFirstSet_VoiceText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VoiceFirstSet_VoiceText_2 {
            get {
                return ResourceManager.GetString("VoiceFirstSet_VoiceText_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   우과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VoiceFirstSet_VoiceText_3 {
            get {
                return ResourceManager.GetString("VoiceFirstSet_VoiceText_3", resourceCulture);
            }
        }
    }
}
